CI : switch to go 1.7
go.uber.org/zap require go verion >= 1.7

or failed : go.uber.org/zap/stacktrace.go:63: undefined: runtime.CallersFrames

Signed-off-by: Nicolas PLANEL <nplanel@redhat.com>